version: "3"

services:
  godori-service:
    build: ./product
    volumes:
      - ./product:/app # it will see the live code changes as they happen
    ports:
      - 5001:80

  website-php:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on: # godori-service가 돌고 있어야 website도 동작한다
      - godori-service

  website-pure:
    image: alpine
    # build: ./website-pure
    volumes:
      - ./pure:/app
    ports:
      - 5003:80
    depends_on:
      - godori-service
